// list & export all action types
const CHANGE_VIEWPORT = "CHANGE_VIEWPORT"
const OPEN_POPUP = "OPEN_POPUP"
const CLOSE_POPUP = "CLOSE_POPUP"
const FETCH_SPOTS = "FETCH_SPOTS"
const UPDATE_USER_MARKER = "UPDATE_USER_MARKER"
const CLAIM_SPACE = "CLAIM_SPACE"
const HANDLE_FORM_CHANGE = "HANDLE_FORM_CHANGE"

export {
  CHANGE_VIEWPORT,
  OPEN_POPUP,
  CLOSE_POPUP,
  FETCH_SPOTS,
  UPDATE_USER_MARKER,
  CLAIM_SPACE,
  HANDLE_FORM_CHANGE
}
