// list & export all action types
const CHANGE_VIEWPORT = "CHANGE_VIEWPORT"
const OPEN_POPUP = "OPEN_POPUP"
const CLOSE_POPUP = "CLOSE_POPUP"
const FETCH_SPOTS = "FETCH_SPOTS"
const UPDATE_USER_MARKER = "UPDATE_USER_MARKER"
const CLAIM_SPACE = "CLAIM_SPACE"
const HANDLE_FORM_CHANGE = "HANDLE_FORM_CHANGE"
const HANDLE_SUBMIT = "HANDLE_SUBMIT"
const NEW_SPACE = "NEW_SPACE"
const OPEN_SPACE = "OPEN_SPACE"
const SHOW_SPACE = "SHOW_SPACE"
const CANCEL_CLAIM = "CANCEL_CLAIM"
const REMOVE_SPACE = "REMOVE_SPACE"
const GO_TO = "GO_TO"
const SHOW_DISTANCE = "SHOW_DISTANCE"
const SET_POSITION = "SET_POSITION"
const UPDATE_TIMER = "UPDATE_TIMER"
const TOGGLE_SHOW_DIRECTIONS = "TOGGLE_SHOW_DIRECTIONS"
const UPDATE_CHATS = "UPDATE_CHATS"
const OPEN_CHAT = "OPEN_CHAT"
const ADD_CHAT = "ADD_CHAT"
const ADD_MESSAGE = "ADD_MESSAGE"
const SET_USER = "SET_USER"
const CLOSE_CHAT = "CLOSE_CHAT"
const TOGGLE_LOADING = "TOGGLE_LOADING"
const FETCH_USERS = "FETCH_USERS"
const ADD_USER = "ADD_USER"
const ALERT = "ALERT"
const UPDATE_PROGRESS_NEXT = "UPDATE_PROGRESS_NEXT"
const UPDATE_PROGRESS_PREV = "UPDATE_PROGRESS_PREV"
const UPDATE_NOTIFICATIONS = "UPDATE_NOTIFICATIONS"
const TOGGLE_NOTIFICATIONS = "TOGGLE_NOTIFICATIONS"
const UPDATE_ACTIVE_SPACE = "UPDATE_ACTIVE_SPACE"
const HIDE_CHAT = "HIDE_CHAT"
const MAP_STYLE = "MAP_STYLE"
const CLOSE_NOTIFICATIONS = "CLOSE_NOTIFICATIONS"
const CLOSE_ACTIVE_NOTIFICATION = "CLOSE_ACTIVE_NOTIFICATION"
const SEE_FAVORITES = "SEE_FAVORITES"
const SET_FAVORITES = "SET_FAVORITES"
const ADD_FAVORITE = "ADD_FAVORITE"
const REMOVE_FAVORITE = "REMOVE_FAVORITE"
const REMOVE_ALL_NOTIFICATIONS = "REMOVE_ALL_NOTIFICATIONS"
const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION"
const ADD_NOTIFICATION = "ADD_NOTIFICATION"
const UPDATE_USER = "UPDATE_USER"
const REMOVE_SPACE_LOG = "REMOVE_SPACE_LOG"
const REMOVE_ALL_USER_SPACES = "REMOVE_ALL_USER_SPACES"
const TOGGLE_LOADING_USER = "TOGGLE_LOADING_USER"
const CREATE_AFTER_PARK = "CREATE_AFTER_PARK"
const PARKED = "PARKED"

export {
  TOGGLE_LOADING_USER,
  REMOVE_ALL_USER_SPACES,
  REMOVE_SPACE_LOG,
  UPDATE_USER,
  CHANGE_VIEWPORT,
  OPEN_POPUP,
  CLOSE_POPUP,
  FETCH_SPOTS,
  UPDATE_USER_MARKER,
  CLAIM_SPACE,
  HANDLE_FORM_CHANGE,
  HANDLE_SUBMIT,
  NEW_SPACE,
  OPEN_SPACE,
  SHOW_SPACE,
  CANCEL_CLAIM,
  REMOVE_SPACE,
  GO_TO,
  SHOW_DISTANCE,
  SET_POSITION,
  UPDATE_TIMER,
  TOGGLE_SHOW_DIRECTIONS,
  UPDATE_CHATS,
  OPEN_CHAT,
  ADD_CHAT,
  ADD_MESSAGE,
  SET_USER,
  CLOSE_CHAT,
  TOGGLE_LOADING,
  FETCH_USERS,
  ADD_USER,
  ALERT,
  UPDATE_PROGRESS_NEXT,
  UPDATE_PROGRESS_PREV,
  UPDATE_NOTIFICATIONS,
  TOGGLE_NOTIFICATIONS,
  UPDATE_ACTIVE_SPACE,
  HIDE_CHAT,
  MAP_STYLE,
  CLOSE_NOTIFICATIONS,
  CLOSE_ACTIVE_NOTIFICATION,
  ADD_FAVORITE,
  SET_FAVORITES,
  SEE_FAVORITES,
  REMOVE_FAVORITE,
  REMOVE_ALL_NOTIFICATIONS,
  REMOVE_NOTIFICATION,
  ADD_NOTIFICATION,
  CREATE_AFTER_PARK,
  PARKED
}
