// list & export all action types
const CHANGE_VIEWPORT = "CHANGE_VIEWPORT"
const OPEN_POPUP = "OPEN_POPUP"
const CLOSE_POPUP = "CLOSE_POPUP"
const FETCH_SPOTS = "FETCH_SPOTS"
const UPDATE_USER_MARKER = "UPDATE_USER_MARKER"
const CLAIM_SPACE = "CLAIM_SPACE"
const HANDLE_FORM_CHANGE = "HANDLE_FORM_CHANGE"
const HANDLE_SUBMIT = "HANDLE_SUBMIT"
const NEW_SPACE = "NEW_SPACE"
const OPEN_SPACE = "OPEN_SPACE"
const SHOW_SPACE = "SHOW_SPACE"
const CANCEL_CLAIM = "CANCEL_CLAIM"
const REMOVE_SPACE = "REMOVE_SPACE"
const GO_TO = "GO_TO"
const SHOW_DISTANCE = "SHOW_DISTANCE"
const SET_POSITION = "SET_POSITION"
const UPDATE_TIMER = "UPDATE_TIMER"

export {
  CHANGE_VIEWPORT,
  OPEN_POPUP,
  CLOSE_POPUP,
  FETCH_SPOTS,
  UPDATE_USER_MARKER,
  CLAIM_SPACE,
  HANDLE_FORM_CHANGE,
  HANDLE_SUBMIT,
  NEW_SPACE,
  OPEN_SPACE,
  SHOW_SPACE,
  CANCEL_CLAIM,
  REMOVE_SPACE,
  GO_TO,
  SHOW_DISTANCE,
  SET_POSITION,
  UPDATE_TIMER
}
